-- 0013 — Immutable, tamper-evident audit trail.
-- Additive only: does not touch business logic or the verified engine. Turns the
-- existing audit_log into an append-only, hash-chained ledger (institutional
-- control). UPDATE/DELETE are blocked at the database; each row carries a
-- SHA-256 hash of (payload + previous row hash) so any tampering is detectable.

alter table public.audit_log
  add column if not exists seq bigint generated by default as identity,
  add column if not exists prev_hash text,
  add column if not exists row_hash text;

-- Append a link to the hash chain on every insert.
create or replace function public.audit_log_chain()
returns trigger
language plpgsql
security invoker
set search_path = public, extensions, pg_temp
as $$
declare
  v_prev text;
begin
  -- Serialize chain appends so prev_hash is always the true tail.
  perform pg_advisory_xact_lock(hashtext('public.audit_log.chain'));
  select row_hash into v_prev from public.audit_log order by seq desc limit 1;
  v_prev := coalesce(v_prev, repeat('0', 64));
  new.prev_hash := v_prev;
  new.row_hash := encode(digest(
    coalesce(new.seq::text, '') || '|' ||
    coalesce(new.occurred_at::text, '') || '|' ||
    coalesce(new.actor, '') || '|' ||
    coalesce(new.action, '') || '|' ||
    coalesce(new.entity_type, '') || '|' ||
    coalesce(new.entity_id::text, '') || '|' ||
    coalesce(new.detail::text, '') || '|' ||
    v_prev, 'sha256'), 'hex');
  return new;
end $$;

drop trigger if exists trg_audit_log_chain on public.audit_log;
create trigger trg_audit_log_chain
  before insert on public.audit_log
  for each row execute function public.audit_log_chain();

-- Append-only: reject any mutation.
create or replace function public.audit_log_block_mutate()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  raise exception 'audit_log is append-only (immutable); % is not permitted', tg_op;
end $$;

drop trigger if exists trg_audit_log_no_update on public.audit_log;
create trigger trg_audit_log_no_update
  before update on public.audit_log
  for each row execute function public.audit_log_block_mutate();

drop trigger if exists trg_audit_log_no_delete on public.audit_log;
create trigger trg_audit_log_no_delete
  before delete on public.audit_log
  for each row execute function public.audit_log_block_mutate();

-- RLS: the single admin may append and read; nobody may update or delete.
drop policy if exists admin_all on public.audit_log;
drop policy if exists audit_select on public.audit_log;
drop policy if exists audit_insert on public.audit_log;
create policy audit_select on public.audit_log for select to authenticated using (true);
create policy audit_insert on public.audit_log for insert to authenticated with check (true);

-- Verify the whole chain; returns ok=false and the first broken seq on tampering.
create or replace function public.verify_audit_chain()
returns table(ok boolean, checked bigint, first_broken_seq bigint)
language plpgsql
security invoker
set search_path = public, extensions, pg_temp
as $$
declare
  r record;
  v_prev text := repeat('0', 64);
  v_calc text;
  v_broken bigint := null;
  v_n bigint := 0;
begin
  for r in select * from public.audit_log order by seq asc loop
    v_n := v_n + 1;
    v_calc := encode(digest(
      coalesce(r.seq::text, '') || '|' ||
      coalesce(r.occurred_at::text, '') || '|' ||
      coalesce(r.actor, '') || '|' ||
      coalesce(r.action, '') || '|' ||
      coalesce(r.entity_type, '') || '|' ||
      coalesce(r.entity_id::text, '') || '|' ||
      coalesce(r.detail::text, '') || '|' ||
      v_prev, 'sha256'), 'hex');
    if r.row_hash is distinct from v_calc or r.prev_hash is distinct from v_prev then
      v_broken := r.seq;
      exit;
    end if;
    v_prev := r.row_hash;
  end loop;
  return query select v_broken is null, v_n, v_broken;
end $$;

grant execute on function public.verify_audit_chain() to authenticated;
